# Configs

title: "loop-unroller"
name: "loop-unroller"
email: victorbieszka@gmail.com
repository: "bievic/bievic.github.io"

include:
  - _pages
  - assets
  - index.html
exclude:
  - TODO.md
  - README.md
  - "*.org"
  - "*ltximg*"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

# settings for author profile
author:
  name   : "Victor Bieszka"
  avatar : "/assets/images/headshot.jpg"
  bio    : "I love learning new things - especially about compilers, data management systems and WebAssembly."
  location: "Hamburg, Germany"
  github : bievic
  linkedin: victor-bieszka-a567ba151
  email  : victorbieszka@gmail.com


# pagination for blog page
paginate: 1 # number of posts to show
paginate_path: /page:num/

# default YAML front matter
defaults:
  # all
  - scope:
      path: ""
    values:
      layout: single
      mathjax: true
      author_profile: true
      class: wide
      title: " "
      title_separator: "|"
  # posts
  - scope:
      type: posts
    values:
      toc: true
      toc_label: "Contents"
      read_time: false
      comments: true
  # portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      author_profile: false
      excerpt: ""
      sidebar:
        nav: "portfolio"

# collections
collections:
  portfolio:
    output: true
